### ISSUE TITLE
Fails to download when there are invalid characters on filename

### ISSUE THREAD

**Issue by rodolfobandeira** [fduaibs/HotmartCourseDownloader#1]
Hi @fduaibs 

Thanks for putting this project available. I was able to learn how this format of video streaming works a little bit more.

I'd like to highlight an issue when the course name contains invalid characters ex: (`1 - Abc - á, é, í, ó, ú, ü, ñ, ¿, * " '`). A possible solution would be replacing the current `filename` to use a "friendly" string format. Ex: "Abc - 123" -> `abc-123`

```js
filename.toString().toLowerCase().split(/\&+/).join("-and-").split(/[^a-z0-9]/).join("-").split(/-+/).join("-").trim('-')
```

Also, I'm not sure if this is related with the invalid characters issue, but at least on my tests, it is currently downloading only the first video from each playlist and jumping to the next module.

Sorry, I know that a Pull Request to help you would be ideal, but I don't have time at the moment.

**Comment by fduaibs** [comment]
Oi, @rodolfobandeira!

Como vi que você era brasileiro também, vou tomar a liberdade de te responder em português pra ficar mais fácil, espero que não se importe.

Primeiro, queria agradecer por reportar o bug e queria dizer que fico feliz que está usando e que gostou dessa besteirinha que eu fiz hahahaha. Como estou começando ainda e esse foi meu primeiro "projeto", fico feliz de verdade de ver ele sendo útil ao pessoal bem mais experiente na área como você.

Bom, sobre o bug em si, eu fiz alguns testes aqui e o problema, acredito eu, não era nos caracteres especiais. Como a função chrome.downloads.download depende do SO, os únicos caracteres que são inválidos no nome são os caracteres que o SO não permite na criação de pastas/caminhos, no Windows, por exemplo, são \ / : * ? "< > | e já existe uma expressão regular que limpa esses caracteres, ela troca tudo por " -" e depois limpa os espaços duplos, se tiver algum. Exemplo:

nome da aula: Aula 1 | Teste
ficaria primeiro: Aula 1  - Teste
e depois de limpar os espaços duplos: Aula 1 - Teste

E isso acontece pro nome do curso e do módulo também.

courseName = String(courseName).replace(/[\\\/\:\*\?\"\<\>\|]/g, " -");
moduleName = String(moduleName).replace(/[\\\/\:\*\?\"\<\>\|]/g, " -");
videoName = String(videoName).replace(/[\\\/\:\*\?\"\<\>\|]/g, " -");

Ainda pode ser um problema em outros SOs além de Win, Mac e Linux, que não permitem caracteres além desses, mas eu levei em consideração apenas esses 3 quando fiz a expressão regular.

Então, quando eu tava fazendo os testes, eu percebi que a extensão tava falhando em achar o nome do curso e esse era o problema. A Hotmart mudou o nome da classe html que fica a informação do nome do curso e como a extensão acha essas informações a partir do DOM da página, ela não tava encontrando. Isso em si não seria um problema, mas do jeito que eu fiz para montar o caminho do arquivo na hora do download, virou um problema. Exemplo:

A extensão filtra o nome de cada parte individualmente com aquela expressão regular ali de cima e depois monta nesse formato:
PastaDownloadPadrao\NomeCurso\NomeModulo\NomeAula.mp4

Quando a extensão não achava o nome do curso, ficava:
PastaDownloadPadrao\\NomeModulo\NomeAula.mp4

E isso era um caminho inválido no SO, então a função chrome.downloads.download dava erro de filename. Assim que eu arrumei de onde a extensão pega o nome do curso, ela baixou normalmente mesmo com os caracteres especiais, então acredito que esse bug já esteja corrigido.

Agora sobre o outro bug de pular de módulo sem chegar ao fim, eu precisaria que você testasse, se pudesse, se ao corrigir o problema dos nomes, corrigiu esse outro também. Aqui nos cursos que eu testei tá baixando certinho. Caso não tenha corrigido, se você puder mandar qual curso que tá tentando baixar pra eu dar uma olhada, agradeceria.

Eu gostaria de ter conversado contigo por um chat em tempo real, pra não precisar escrever esse blocão de texto, eu achei seu LinkedIn olhando seu perfil, te mandei um convite lá, mas como você disse que tava meio sem tempo, eu quis responder logo por aqui mesmo. Desculpa o bloco de texto hahahaha. 

Vou subir as mudanças agora. Obrigado novamente pela ajuda e desculpa a demora pra responder, abraço, Rodolfo.

**Comment by rodolfobandeira** [comment]
Ola @fduaibs 
Obrigado pelo feedback. Agora, lendo tudo que voce escreveu, realmente lembrei que vi o nome do curso falhando realmente. Eu testei sua extensao em uma virtual machine windows entao concordo contigo com relacao aos caracteres especiais relacionados ao SO.

Infelizmente, so fiz alguns testes para um colega e nem tenho mais acesso a conta para testar suas alteracoes.

Obrigado, Abc!
