### ISSUE TITLE
Ajuda, Dúvida

### ISSUE THREAD

**Issue by Kakunda** [fduaibs/HotmartCourseDownloader#10]
Boa Tarde!
Primeiramente, obrigado por disponibilizar esse código maravilhoso, parabéns pela iniciativa.

Estou anexando, os lugares que verifiquei para poder me ajudar, Preciso entender, o que, ou onde devo configurar a saída, pela analise da extensão, pois só não fez o download do arquivo, na pasta de download não apareceu o arquivo.

![erro](https://user-images.githubusercontent.com/74979006/100123100-e8a41800-2e58-11eb-86f9-867444ba3a00.png)

![erro2](https://user-images.githubusercontent.com/74979006/100126241-77fefa80-2e5c-11eb-9d2d-37f5a928c808.png)

![erro3](https://user-images.githubusercontent.com/74979006/100126428-b1376a80-2e5c-11eb-8588-7d37f4993aa6.png)

Grato. Sucesso!

**Comment by fduaibs** [comment]
Opa, Rafael.

Primeiramente obrigado, fico feliz de verdade que vocês tão usando e gostando.

Quanto ao erro, bom, alguns cursos da Hotmart têm caracteres especiais que o Windows não aceita como caminho/nome de arquivo, ou ainda pior, alguns criadores de conteúdo lá na Hotmart mudam a estrutura da página do curso e isso acaba mudando o arquivo .html, e como a extensão pega as coisas pelo html, ela acaba não achando. No caso dos caracteres do Windows, já existe um filtro que limpa eles e substitui por -, mas no caso das personalizações da página não tem como e eu tentei fazer o mais genérico possível, pra funcionar na maioria dos casos.

No seu caso em específico, parece que é algum problema com o nome do curso, porque o caminho que a extensão salva por padrão é "sua_pasta_de_download_padrão/nome_curso/nome_módulo/nome_aula.mp4" e pelos seus prints me parece que o nome do curso tá em branco.

Um fix rápido disso seria salvar com um nome fixo, aí eu te digo quais linhas de código você tem que alterar. Ou então você poderia me passar o nome do curso que eu tento ver qual foi o problema e sugiro um fix melhor. Se é algo pessoal ou que você não queira postar aqui, pode mandar no meu email, por favor, eu te passo se você precisar.

Eu preciso arrumar isso de verdade, já peguei uns 3 casos que deu problema. Esse fim de semana eu vou tentar arrumar tempo pra mexer na extensão por um todo e vou subir um fix disso, provavelmente. Eu não vou arrumar o frontend ainda, porque eu vou ter que estudar como faz isso de novo porque eu já esqueci hahahaha, mas o backend é de boas.

Fico no aguardo do que você vai preferir fazer, Rafael. Valeu!

**Comment by RafaelRotti** [comment]
Tarde!

Passo por e-mail sim, qual seria ? Ai você avalia melhor, e se quiser tentar também, podemos fixar um nome para teste.

Grato.

**Comment by fduaibs** [comment]
felipe.duaibs@hotmail.com

valeu!

**Comment by RafaelRotti** [comment]
Blz, Enviado.

**Comment by tobeyond** [comment]
Você pode me dizer, também, quais linhas alterar?
