### ISSUE TITLE
Funcionamento;  Progresso de Download; Usabilidade.

### ISSUE THREAD

**Issue by GeOliveiraGe** [fduaibs/HotmartCourseDownloader#11]
Passando para agradecer a iniciativa incrível e também para tirar algumas dúvidas

Aqui está funcionado, mas o sobre o uso ainda não me parece claro. Não consigo perceber ou não enxergo o momento exato em que o download começa, o progresso do download não aparece ou não estou conseguido enxergar em parte alguma o andamento; tudo que me é mostrado é a notificação na parte inferior do navegador assim que o vídeo termina  de ser baixo. Acho que falta isso, algo em que a gente possa perceber o andamento claramente, desde o início e o durante, principalmente (talvez fazer um gifzinho animado e deixar na página do Code mostrando isso. Acontece também de alguns vídeos serem baixados rapidamente, outros não (alguns demoram muito); percebo que alguns baixam quando mudo para outra aba aberta; não sei existe alguma associação. Enfim... Detalhes que fazem a diferença.

Sua ideia é incrível. Não sou especialista em JavaScript, mas sou muito fuçador. Estou à disposição para colaborar com melhorias, caso queira / precise.

**Comment by fduaibs** [comment]
Opa, Ge.

Então, eu vou mudar o readme pra ficar mais claro onde encontra essas mensagens. Acho que foi erro de escrita da minha parte por ter ficado confuso, mas existe um jeito sim, é assim:

- Digitando chrome://extensions/ no campo de url e dando enter;
- Procurando a extensão e clicando no "background.html" dela, que vai estar como um link, em azul;
- Indo na aba console da janela que abrir.

Pronto, as mensagens e o progresso do download ficam nessa janela. 

Eu pretendo fazer o frontend (com mensagens, ícones, opções, e etc) e refatorar o backend em breve (ainda mais agora que o pessoal tá interagindo bastante aqui no repositório, tá me dando um incentivo a mais :D ), então eu vou tentar juntar todo o feedback e os reports de bug que deram e lançar uma versão 1.0 e colocar na lojinha de extensão do Chrome, pra ficar mais fácil de instalar e receber atualizações conforme eu for fazendo. O meu único problema atualmente é tempo, porque hoje em dia eu trabalho em horário comercial, mas vou fazer o melhor que eu puder.

Sobre a questão das abas, você pode ficar a vontade pra mudar de aba porque ela usa o id da aba pra "garimpar" as informações que ela precisa, então o único problema é que "notificação" do arquivo de download aparecendo embaixo, vai aparecer na aba que você tiver com foco, mas as informações SEMPRE vão ser pegas da aba em que você clicou na extensão.

Sobre contribuir com o projeto, bom, é aberto e você pode fazer o que quiser com o código, dando os devidos créditos. Mas se você tiver afim de implementar alguma melhoria e mandar um pull request, vai ser muito bem vindo :)

No mais, agradeço de verdade as palavras e fico muito feliz que o pessoal tá usando. Os últimos dias foram bem legais, teve bastante interação por aqui, recebi mais mensagem nesse tempo do que de todos os outros meses, desde que eu postei.

Se tiver mais alguma dúvida/sugestão, pode ficar à vontade!

Valeu!

**Comment by GeOliveiraGe** [comment]
Maravilha, irmão! 

Sobre o andamento do download, agora sim ficou claro com o que você escreveu aqui. Dá mesmo para acompanhar lá.

Caram _frontend_ será o pulo do gato, e, claro, o _backend_ notificado também, pois isso vai fazer a extensão chegar (e ser aceita) aos/pelos 'meros mortais'. Quanto ao local onde o arquivo é salvo, é muito importante deixar isso para que o usuário escolha onde salvá-lo, através de janela seletiva, e/ou pré-configuração em opções da extensão. Vá em frente e conta comigo! 

Notei que a extensão reconhece como "curso" apenas o conteúdo contido em única pasta, parando a automação do download após o término do download do último vídeo ou do único vídeo da pasta selecionada / ativa, e também ao se deparar com um conteúdo interativo ou com um conteúdo em PDF entre um vídeo e outro. Dica: seria interessante criar um código para pegar o PDF automaticamente também, uma vez que os cursos do Hotmart quase sempre têm algum PDF como material de apoio.

Outro detalhe: para ficar ainda mais didático, melhor mudar o texto para "Pressione **E SEGURE** o botão da extensão por 10 segundos..." (se não engano, pelo que vi, essa ação é necessária para que a extensão _resete_ as informações do download do conteúdo da pasta baixado e fique pronta para o próximo download); e isso meio que "desliga" a extensão; para mim, após essa ação, é necessário um novo clique na mesma, para religá-la, para só assim, ela conseguir baixar um outro vídeo selecionado / ativo em uma nova pasta. E nem sempre é necessário segurar os 10 segundos para o reset, basta um clique para isso, após os primeiros downloads, e um novo clique para que o novo download se inicie.

**PROBLEMA e PEDIDO de AJUDA**: uma das pastas do curso que usei como teste não teve seu conteúdo encaminhado para a pasta de download normalmente, assim como foram os outros vídeos, apesar de eu acompanhar todo o andamento do download normal no console da extensão, e sem notificação de erro. Talvez isso tenha a ver com o nome da pasta ou dos arquivos, apesar de eu achar que não faz muito sentido, pois os caracteres são todos normais (latinos). Pergunto: existe alguma pasta temporária para onde os arquivos são encaminhados antes de serem organizados nas pastas dos downloads específicos, ou esses arquivos "baixados" ficarão perdidos no limbo? Se houver essa pasta eu posso coletar os arquivos de lá e organizar manualmente; se não, é algo a ser corrigido nas novas versões. Preciso muito dessa basta, é um curso compartilhado por um amigo, que procurava há algum tempo uma solução para download no Hotmart, já que ele odeia estudar direto por lá. Fico grato desde já se puder me ajudar com essa única pasta problema (consegui baixar 27 pastas, apenas uma deu problema).

Grande abraço e estou de prontidão por aqui.

**Comment by fduaibs** [comment]
Então, Ge, vamos por partes.

Eu pretendo colocar a opção da pessoa escolher onde a extensão vai baixar quando eu for fazer as melhorias. O problema aqui é que na API do Chrome teoricamente tem como você escolher se vai aparecer a janela de perguntar onde a pessoa quer salvar, ou se vai salvar no diretório padrão onde ela já configurou pelo próprio Chrome, mas essa opção estava quebrada quando eu usei a API, não sei se já arrumaram. Acho que algo fora dessas opções não seja possível.

Sobre ela parar quando aparecer algum conteúdo interativo ou PDF, de fato acontece, eu pensei em colocar um tratamento disso, mas como eu tava fazendo pensando só em eu usar - nem tinha pensando em colocar aqui -, pra mim era mais fácil pular na mão mesmo e colocar pra ela baixar de novo no próximo vídeo. Eu não sei se tem como criar um regra que funcione em todos os casos nesse ponto, teria que estudar um pouco a estrutura de página da Hotmart de novo, e o mais importante, preciso de casos de teste, coisa que eu também não tinha quando tava fazendo. Eu tinha só 3 cursos na Hotmart kkkkk. 

Sobre reconhecer "pastas" como curso ou não, eu não entendi esse ponto direito, vou tentar responder, é de acordo com o menu lateral e o nome. O nome é só pra questão de salvar e não substituir por estar com o mesmo nome no mesmo diretório. Mas o que ela define como fim de curso e para de baixar é quando chega no último elemento **interno** do menu lateral.

O ponto de segurar por 10s ou apenas apertar, eu acho que você (ou talvez eu tenha entendido errado o que você quis dizer) entendeu um pouco errado como funciona. Um conteúdo da Hotmart, até onde eu sei, é dividido por curso, módulo e aulas. Vamos supor pra fins de exemplo que seja um mundo ideal que só tenha aulas e não tenha PDFs, aulas duplas na mesma página, ou conteúdos interativos. A extensão deveria conseguir baixar o curso todo automático, pra isso, você tem que ir na primeira aula do primeiro módulo e apertar o botão da extensão (**não segurar**), ela vai dar um tempo de 10s, pra garantir que a página tá carregada e vai começar a baixar. Nesse ponto, você pode trocar de aba à vontade, ela usa o id da aba que você clicou pra pegar as informações, então não tem problema. Quando ela terminar de baixar a primeira aula, ela vai pra segunda aula sozinha, você vai ver a aba do Chrome mudando de url e atualizando. Quando isso acontecer, ela vai aguardar mais 10s pra página carregar e vai começar a baixar, e assim sucessivamente, em todas as aulas desse módulo e de todos os outros também, até o menu lateral acabar. Quando o menu acabar, ela vai dar uma mensagem escrita "End of the Course", algo assim. 
Você não precisa fazer mais nada nesse cenário feliz, até o curso acabar. Mas caso você clique de novo no botão da extensão quando ela tá em funcionamento, ela vai parar, pra ela voltar a funcionar, você tem que clicar de novo, aí ela vai dar o tempo de 10s e vai voltar a baixar até o final do curso novamente. Nesses casos que você interrompeu o funcionamento dela no meio do processo, obviamente você tem que clicar nela de novo onde na página da aula que ela parou, você tem que fazer isso manualmente. Se por uma acaso você interrompeu ela na metade do curso e você voltar pra primeira aula e clicar de novo, ela vai baixar essa primeira metade inteira de novo, sobrescrevendo um vídeo por outro na pasta de download.
Agora voltando pros cenários que tem PDF, ou qualquer coisa que não seja aulas, você tem que interromper o funcionamento dela (se ela não fizer isso sozinha), pular pra próxima aula, que seja de fato uma aula, e clicar de novo.

Não sei se ficou claro esse último ponto, mas resumindo, ela só tem dois estados, ou ela tá parada, ou ela tá baixando e vai baixar até o final do curso se não tiver nenhuma pedra no caminho. Esse processo é uma recursão.

Sobre o problema 1 - Nunca vi esse erro antes e é bem estranho na verdade, e se não tem nenhuma mensagem de erro, não sei nem o que te responder, teria que debugar. Sim, existe um lugar mas eu não lembro de cabeça, sugiro você pesquisar onde o Chrome guarda os blobs. Eu sei que tem porque eu tava em dúvida de um problema de estouro de ram se o vídeo fosse muito grande e tive que pesquisar isso, e no final das contas, o Chrome guarda em disco. No próprio console aparece a url do blob antes da mensagem que o download foi feito. Se você for ninja em conseguir clicar ou copiar essa url, você consegue colar ela em outra aba e consegue baixar por lá também. Essa url começa com "blob: asjudsaudhasiudasdasdoassd" algo assim.

Sobre o problema 2 - Isso já é um problema conhecido. O pessoal que abriu outra issue sugeriu um fix mais pontual pra esse caso, dá pra você olhar lá se quiser. Esse ponto de correção já tá no to do. Eu vou olhar o link que você mandou, valeu.

No mais, acho que é isso. Ficou gigantesco, mas é complexo de explicar por texto, foi mal kkkkkkkk

Se tiver mais algum ponto, pode ficar à vonts.

Valeu!
