### ISSUE TITLE
Problem getting video qualities

### ISSUE THREAD

**Issue by fernandoluizao** [fduaibs/HotmartCourseDownloader#2]
I'm trying to download a course, but the extension downloads just the first lesson. 
Investigating the issue, I realized that the video qualities returned by hotmart in the first video differs from the rest:

1st video:
```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=366321,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=426x240
240/240.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=603399,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=640x360
360/360.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1036316,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=960x540
540/540.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1495250,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x720
720/720.m3u8
```

Other videos:
```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=305013,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=640x400
400/0d27bfaf-f4f8-457a-8369-8352dd19cf7d.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=454940,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x800
800/85a0cc81-d47d-4115-abd1-31ffa51e8c79.m3u8
```

I did some changes and managed to download all the lessons. Would you accept a pull request for handling cases like this?

**Comment by fduaibs** [comment]
Opa, Fernando.

Como você é brasileiro também, vou te responder em português.

Primeiramente, muito obrigado pela sua contribuição e pelo seu tempo. Claro que eu aceito seu PR.
Uma coisa que eu não tinha pensando antes de começar a desenvolver a extensão é que a Hotmart permite muitos jeitos de hospedar os cursos, o que gera uma grande diversidade de casos. Nos meus casos (bem limitados, por sinal) de teste, eu não cheguei a me deparar com um caso assim. Outro problema também é que a Hotmart constantemente muda a estrutura do DOM, e como a extensão pega as coisas de lá, acaba tendo que de vez em quando atualizar a extensão.  Mas fico feliz que você conseguiu baixar. 

Agradeço novamente, Fernando. Tamo junto!

**Comment by fernandoluizao** [comment]
Eu que agradeço, muito útil a extensão. Só falta algum feedback visual, % do download, quando dá algum erro... tive que descobrir como debugar uma extensão hehehe, não manjo nada de escrever extensões. 

Abraço!
