### ISSUE TITLE
Issue quando tem 2 ou mais video na mesma página

### ISSUE THREAD

**Issue by shpsyte** [fduaibs/HotmartCourseDownloader#4]
Fala @fduaibs

Obrigado por deixar o projeto disponivel, ele é top!

Quando uma pagina possui 2 ou mais videos, ao terminar o primeiro video ele muda de página deixando a parte 2,3,4... para traz.

Bom, eu comentei as linhas para que ele não pule automaticamente, mas seria legal antes de ele pular de pagina verificar se existe estes "passos", nao sei qual a complexidade disso.
Até tentei (eu ainda vou tentar mudar isso).... 

![image](https://user-images.githubusercontent.com/3891610/91101690-7551f680-e61c-11ea-972c-aa2f14645917.png)

**Comment by fduaibs** [comment]
Opa, @shpsyte.

Primeiramente, desculpa a demora pra responder, eu tô meio sem tempo ultimamente. Como eu expliquei na outra issue, quando eu tava fazendo a extensão, meus casos de teste eram muito limitados. Eu não tinha muitos cursos na minha conta da Hotmart, então eu fiz só pra funcionar com os que eu tinha.
Eu tô trabalhando full time agora e não pretendo mexer aqui tão cedo, mas eu não abandonei o projeto, com certeza ainda vou atualizar ele algum dia com o que falta no "to-do" (até por necessidade, porque eu tinha acabado de começar com javascript quando eu fiz a extensão e ela tá bem mal escrita, não condiz com o jeito que eu programo hoje em dia kkkkk) e quando isso acontecer eu vou tentar ver se consigo um caso de teste pra fazer funcionar nessas ocasiões também.
Agradeço de verdade o feedback e caso queira sugerir algo a mais, pode ficar a vontade!

Abraço, José!

**Comment by Romulossp** [comment]
Ola @shpsyte e @fduaibs, desculpe me intrometer nesta issue mas estou sofrendo o mesmo problema que @shpsyte ( Página com mais de 1 vídeo ) gostaria de saber qual linha foi comentada.

Grato.

**Comment by eloisemonteiro** [comment]
Eu cai em um erro: background.html:1 Unchecked runtime.lastError: Invalid filename
Alguém teria uma luz?

**Comment by shpsyte** [comment]
Fala @Romulossp so vi agora sua msg

Comentei:

chrome.tabs.update(currentTab, { url: nextVideo });
perto da linha 318 (pq estou fazendo outras alteracoes)

e
doAgain(currentTab); perto da linha 341

ambas no arquivo background.js


Ai ele nao pula a página e fica esperando vc dar o inicio novamente
