### ISSUE TITLE
Not downloading videos and showing error on Console

### ISSUE THREAD

**Issue by MikeDoouglas** [fduaibs/HotmartCourseDownloader#7]
Primeiramente, ótima extensão, parabéns!

O problema é o seguinte, após os 10 segundos, ele gera um erro no console.

![Captura de tela de 2020-11-22 15-12-55](https://user-images.githubusercontent.com/28317024/99911848-c930b200-2cd5-11eb-925b-2eabd1fa821e.png)

**Comment by MikeDoouglas** [comment]
Deixa pra lá, eu pensei que não tinha funcionado porque cliquei, esperei, e nada aconteceu, só o erro, mas um tempão depois o video baixou, é que o video tinha 100+ mega, então demorou e não deu feedback.

**Comment by fduaibs** [comment]
E aí, Mike, tudo bom?

O feedback pode ser encontrado no console da extensão. Ele é diferente do console do Chrome em si. Você pode achar ele digitando chrome://extensions/ na url e clicando em cima do "background.js" da extensão, que está como um link, em azul, aí vai abrir o devtools específico da extensão e você pode ir na aba console por lá que você vai conseguir ver as mensagens e o progresso de download.

Infelizmente quando eu tava fazendo eu não tive tempo de fazer um frontend decente e acabou que ficou assim mesmo. Como eu disse em outras issues, um dia ainda vou lançar o v2 com melhorias na escrita do código (eu tinha acabado de começar com JS na época e não corresponde mais à minha qualidade de código atualmente), com um frontend de gente e com um formato .mp4 de verdade pra funcionar em qualquer player ~~só não sei quando kkkkkkk~~.

Fico feliz que tenha gostado e se tiver mais alguma dúvida pode ficar à vontade!

Abraço!
