### ISSUE TITLE
Nao funcionou

### ISSUE THREAD

**Issue by kongdonkeyking** [fduaibs/HotmartCourseDownloader#8]
Comigo nao funcionou nao. Tentei de tudo que é jeito e nao vai...

**Comment by fduaibs** [comment]
Opa, tudo bom?

Poderia ser mais específico em qual parte não conseguiu ou está com dúvidas? 
Sem mais detalhes fica difícil tentar te ajudar.

Fico no aguardo. Valeu!

**Comment by kongdonkeyking** [comment]
ah sim sim. eu instalei no meu Chrome e não consigo baixar vídeos da Hotmart. clico no play, esperei mais de 10 segundos, cheguei ate a esperar o vídeo inteiro carregar, mas o icone nao muda de cor e ao clicar nao acontece nada...

**Comment by fduaibs** [comment]
Não acontece nada mesmo quando você clica, eu ainda não terminei de fazer a extensão, então a parte visual não tá pronta. Você pode ver as mensagens e o progresso do download fazendo o seguinte:

- Digitando chrome://extensions/ no campo de url e dando enter;
- Procurando a extensão e clicando no "background.html" **dela**, que vai estar como um link, em azul;
- Indo na aba console da janela que abrir.

Agora vai aparecer as mensagens. Peço por favor que você tente baixar de novo e tire um print dessa janela do console após você clicar e esperar uns 30s. E um print do vídeo que você está tentando baixar, por gentileza.

Fico no aguardo. Valeu!

**Comment by kongdonkeyking** [comment]
tentei também e nada acontece. gravei um video mando por onde?... valeu

**Comment by fduaibs** [comment]
Pode mandar no meu felipe.duaibs@hotmail.com

**Comment by kongdonkeyking** [comment]
enviado amigo. obrigado.

**Comment by MikeDoouglas** [comment]
> Não acontece nada mesmo quando você clica, eu ainda não terminei de fazer a extensão, então a parte visual não tá pronta. Você pode ver as mensagens e o progresso do download fazendo o seguinte:
> 
> * Digitando chrome://extensions/ no campo de url e dando enter;
> * Procurando a extensão e clicando no "background.html" **dela**, que vai estar como um link, em azul;
> * Indo na aba console da janela que abrir.
> 
> Agora vai aparecer as mensagens. Peço por favor que você tente baixar de novo e tire um print dessa janela do console após você clicar e esperar uns 30s. E um print do player do vídeo que você está tentando baixar, por gentileza.
> 
> Fico no aguardo. Valeu!

Mano, eu estou usando essa extensão desde ontem, e já baixei 30 videos sem saber disso, procurei em todo lugar essa informação de onde ver o progresso dos Downloads, tem como colocar isso no README?

Eu estou utilizando a extensão sem saber se está ou não baixando o video, eu só clico e espero, se baixar em uns 10~20 minutos é porque funcionou hahaha.

Muito boa essa extensão!

**Comment by fduaibs** [comment]
> > Não acontece nada mesmo quando você clica, eu ainda não terminei de fazer a extensão, então a parte visual não tá pronta. Você pode ver as mensagens e o progresso do download fazendo o seguinte:
> > 
> > * Digitando chrome://extensions/ no campo de url e dando enter;
> > * Procurando a extensão e clicando no "background.html" **dela**, que vai estar como um link, em azul;
> > * Indo na aba console da janela que abrir.
> > 
> > Agora vai aparecer as mensagens. Peço por favor que você tente baixar de novo e tire um print dessa janela do console após você clicar e esperar uns 30s. E um print do player do vídeo que você está tentando baixar, por gentileza.
> > Fico no aguardo. Valeu!
> 
> Mano, eu estou usando essa extensão desde ontem, e já baixei 30 videos sem saber disso, procurei em todo lugar essa informação de onde ver o progresso dos Downloads, tem como colocar isso no README?
> 
> Eu estou utilizando a extensão sem saber se está ou não baixando o video, eu só clico e espero, se baixar em uns 10~20 minutos é porque funcionou hahaha.
> 
> Muito boa essa extensão!

Opa, Mike!

Eu respondi isso na sua issue também, não sei se você viu. E sobre colocar no readme, na verdade já está, só não tá tão explícito kkkkkkk, olha só:

> 2.3 - The extension will start to download it, and once done, it will save at "your default download folder/course name/module
> name/video name.mp4". **You can see the progress on the extention background script console**. Once done, it will go to the > next class and repeat.

Mas eu vou mudar lá pra deixar mais claro.

Valeu pelo feedback, galera, que bom que estão usando e gostando.

**Comment by MikeDoouglas** [comment]
> > > Não acontece nada mesmo quando você clica, eu ainda não terminei de fazer a extensão, então a parte visual não tá pronta. Você pode ver as mensagens e o progresso do download fazendo o seguinte:
> > > 
> > > * Digitando chrome://extensions/ no campo de url e dando enter;
> > > * Procurando a extensão e clicando no "background.html" **dela**, que vai estar como um link, em azul;
> > > * Indo na aba console da janela que abrir.
> > > 
> > > Agora vai aparecer as mensagens. Peço por favor que você tente baixar de novo e tire um print dessa janela do console após você clicar e esperar uns 30s. E um print do player do vídeo que você está tentando baixar, por gentileza.
> > > Fico no aguardo. Valeu!
> > 
> > 
> > Mano, eu estou usando essa extensão desde ontem, e já baixei 30 videos sem saber disso, procurei em todo lugar essa informação de onde ver o progresso dos Downloads, tem como colocar isso no README?
> > Eu estou utilizando a extensão sem saber se está ou não baixando o video, eu só clico e espero, se baixar em uns 10~20 minutos é porque funcionou hahaha.
> > Muito boa essa extensão!
> 
> Opa, Mike!
> 
> Eu respondi isso na sua issue também, não sei se você viu. E sobre colocar no readme, na verdade já está, só não tá tão explícito kkkkkkk, olha só:
> 
> > 2.3 - The extension will start to download it, and once done, it will save at "your default download folder/course name/module
> > name/video name.mp4". **You can see the progress on the extention background script console**. Once done, it will go to the next class and repeat.
> 
> Mas eu vou mudar lá pra deixar mais claro.
> 
> Valeu pelo feedback, galera, que bom que estão usando e gostando.

É eu fui procurar depois que comentei e vi essa parte, eu lembro que na primeira vez eu li mas não entendi, pensei que era o Console da própria página da Hotmart, mas cara, de novo gostaria de elogiar a exntesão, ta sensacional, parabéns!

**Comment by fduaibs** [comment]
@MikeDoouglas Valeu, mano, fico feliz de vdd.

@kongdonkeyking posso fechar a issue? Tudo certo aí né?

**Comment by fduaibs** [comment]
Como ajudei pessoalmente o @kongdonkeyking e tinha dado certo, vou fechar a issue.
