### ISSUE TITLE
Não importa no Chrome

### ISSUE THREAD

**Issue by thiago080390** [fduaibs/HotmartCourseDownloader#9]
Opa!! Beleza?
Cara, baixei o .zip, extraí no downloads e apontei lá no Chrome (já em modo desenvolvedor) para a pasta. Na verdade tentei apontar para todas as pastas, uma a uma e nada disso funcionou.
O erro que ele dá é: 
"Falha ao carregar extensão.
O arquivo de manifesto está faltando ou não pode ser lido
Não foi possível carregar o manifesto."

Pode ajudar?

**Comment by fduaibs** [comment]
Opa, Thiago.

A pasta que você deve apontar é a que surge assim que você deszipa, no meu caso aqui foi a "HotmartCourseDownloader-master".

Essa falha de manifesto é que o arquivo manifest.json não tá sendo encontrado ou está corrompido. Ele é necessário pois contém as permissões e as configurações da extensão. O meu palpite é que talvez possa ter baixado corrompido ou algum programa de proteção seu (não deveria, mas) deletou. O que eu posso te dizer pra fazer é pra tentar baixar novamente e ver se de fato os arquivos que vieram na pasta batem com os que tão aqui no Github.

Caso continue com problema após às 18 posso te ajudar melhor.

Fico no aguardo. Valeu!

**Comment by thiago080390** [comment]
Deletei tudo, extraí novamente e funcionou. Realmente o .json não estava lá!
Vou testar agora. Valeu!
